apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ggml
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mdbi-tenant/rhtap-demo-app/hacbs-test-project-ggml@sha256:fe5855eab62a16ab610525a19ef293a0227bf08bce07df124920a14d0019c8bf
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
